### ISSUE TITLE
Cannot find module '@xviz/io/node'

### ISSUE THREAD

**Issue by JunkyDeveloper** [aurora-opensource/xviz#688]
I run the run_kitti script directly after the download script and i got this error
`./run-kitti-example.sh 
Generating default KITTI XVIZ data
yarn install v1.22.17
warning package.json: No license field
info No lockfile found.
warning jskitti@1.1.0: No license field
[1/4] Resolving packages...
warning uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
warning xml2json > joi@13.7.0: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
warning xml2json > hoek@4.2.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
warning xml2json > joi > hoek@5.0.4: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
warning xml2json > joi > topo@3.0.3: This module has moved and is now available at @hapi/topo. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
warning xml2json > joi > topo > hoek@6.1.3: This module has moved and is now available at @hapi/hoek. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
warning babel-polyfill > core-js@2.6.12: core-js@<3.4 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
warning babel-polyfill > babel-runtime > core-js@2.6.12: core-js@<3.4 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
Done in 28.94s.
yarn run v1.22.17
warning package.json: No license field
$ node ./src/index.js -d /home/tufast/xviz/scripts/../data/kitti/2011_09_26/2011_09_26_drive_0005_sync -o /home/tufast/xviz/scripts/../data/generated/kitti/2011_09_26/2011_09_26_drive_0005_sync/
internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module '@xviz/io/node'
Require stack:
- /home/tufast/xviz/examples/converters/kitti/src/transform.js
- /home/tufast/xviz/examples/converters/kitti/src/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.<anonymous> (/home/tufast/xviz/examples/converters/kitti/src/transform.js:16:1)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Module._compile (/home/tufast/xviz/examples/converters/kitti/node_modules/pirates/lib/index.js:136:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Object.newLoader [as .js] (/home/tufast/xviz/examples/converters/kitti/node_modules/pirates/lib/index.js:141:7)
    at Module.load (internal/modules/cjs/loader.js:950:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/tufast/xviz/examples/converters/kitti/src/transform.js',
    '/home/tufast/xviz/examples/converters/kitti/src/index.js'
  ]
}
error Command failed with exit code 1.
`

I have node 14 because of some other issues from streetscape.gl (globalThis)

**Comment by JunkyDeveloper** [comment]
in avs.auto is the documentation wrong. you need to run yarn bootstrap without that it makes that error
